laser_scan_filter_chain:
  - name: angle_filter
    type: laser_filters/ScanAngleFilter
    params:
      lower_angle: -1.57   # -90 degrees in radians
      upper_angle: 1.57    # +90 degrees in radians
